# Generated by Django 3.2.5 on 2022-12-26 16:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('address', models.TextField()),
            ],
        ),
    ]
