# Generated by Django 3.2.5 on 2023-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalratecategory',
            name='rate_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ratecategory',
            name='rate_category',
            field=models.CharField(max_length=255),
        ),
    ]
