# Generated by Django 3.2.5 on 2023-02-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forex',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='historicalforex',
            name='tax',
        ),
    ]
