# Generated by Django 3.2.5 on 2022-12-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=250)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='reservations.property')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.block')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='reservations.property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('max_adults', models.PositiveSmallIntegerField()),
                ('max_children', models.PositiveSmallIntegerField()),
                ('total_number_of_rooms', models.PositiveSmallIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='reservations.property')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveSmallIntegerField()),
                ('room_status', models.CharField(choices=[('clean', 'Clean'), ('inspected', 'Inspected'), ('dirty', 'Dirty'), ('out_of_order', 'Out of Order'), ('out_of_service', 'Out of Service')], max_length=100)),
                ('front_office_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], max_length=100)),
                ('reservation_status', models.CharField(choices=[('assigned', 'Assigned'), ('departed', 'Departed'), ('stay_over', 'Stay Over'), ('arrivals', 'Arrivals'), ('not_reserved', 'Not Reserved'), ('arrived', 'Arrived'), ('due_out', 'Due Out'), ('due_out_arrivals', 'Due Out / Arrivals')], max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.floor')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.roomtype')),
            ],
        ),
    ]
