# Generated by Django 3.2.5 on 2023-01-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_roomtype_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroom',
            name='room_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
