# Generated by Django 3.2.5 on 2022-12-27 12:25

from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_block_floor_room_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overbooking_limit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.CreateModel(
            name='RoomTypeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_available_rooms', models.PositiveSmallIntegerField()),
                ('number_of_overbooked_rooms', models.PositiveSmallIntegerField(validators=[reservations.models.validate_max_number_of_overbooked_rooms])),
                ('date', models.DateField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='reservations.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_office_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], max_length=100)),
                ('housekeeping_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], max_length=100)),
                ('front_office_pax', models.PositiveSmallIntegerField()),
                ('housekeeping_pax', models.PositiveSmallIntegerField()),
                ('discrepancy', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_discrepancies', to='reservations.room')),
            ],
            options={
                'verbose_name_plural': 'Room Discrepancies',
            },
        ),
    ]
