# Generated by Django 3.2.5 on 2023-02-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20230201_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjusttransaction',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjust_transactions', to='reservations.transaction'),
        ),
        migrations.AddField(
            model_name='historicaladjusttransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.transaction'),
        ),
    ]
