# Generated by Django 3.2.5 on 2023-01-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('reservations', '0003_auto_20230124_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='company_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='reservations.room'),
        ),
    ]
