# Generated by Django 3.2.5 on 2023-02-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20230201_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_details', to='reservations.reservation'),
        ),
    ]
