# Generated by Django 3.2.5 on 2022-12-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20221227_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproperty',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='modified_by',
        ),
    ]
