# Generated by Django 3.2.5 on 2022-12-27 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0009_auto_20221227_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extras',
            new_name='Extra',
        ),
        migrations.RenameModel(
            old_name='HistoricalExtras',
            new_name='HistoricalExtra',
        ),
        migrations.AlterModelOptions(
            name='historicalextra',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical extra', 'verbose_name_plural': 'historical extras'},
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='extras_code',
            new_name='extra_code',
        ),
        migrations.RenameField(
            model_name='historicalextra',
            old_name='extras_code',
            new_name='extra_code',
        ),
    ]
