# Generated by Django 3.2.5 on 2022-12-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20221227_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='historicalextra',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='extra',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextra',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
