# Generated by Django 3.2.5 on 2022-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20221228_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
