# Generated by Django 3.2.5 on 2023-01-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20230107_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='document',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='file_upload',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='ticket_files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='reservations.invoice'),
        ),
    ]
