# Generated by Django 3.2.5 on 2023-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20230107_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forex',
            options={'verbose_name_plural': 'Forex'},
        ),
        migrations.AlterModelOptions(
            name='historicalforex',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical forex', 'verbose_name_plural': 'historical Forex'},
        ),
        migrations.AlterModelOptions(
            name='historicalratecategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical rate category', 'verbose_name_plural': 'historical Rate Categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalrateclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical rate class', 'verbose_name_plural': 'historical Rate Classes'},
        ),
        migrations.AlterModelOptions(
            name='historicalroomoccupancy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical room occupancy', 'verbose_name_plural': 'historical Room Occupancies'},
        ),
        migrations.AlterModelOptions(
            name='historicalticketcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ticket category', 'verbose_name_plural': 'historical Ticket Categories'},
        ),
        migrations.AlterModelOptions(
            name='ratecategory',
            options={'verbose_name_plural': 'Rate Categories'},
        ),
        migrations.AlterModelOptions(
            name='rateclass',
            options={'verbose_name_plural': 'Rate Classes'},
        ),
        migrations.AlterModelOptions(
            name='roomoccupancy',
            options={'verbose_name_plural': 'Room Occupancies'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name_plural': 'Ticket Categories'},
        ),
        migrations.AddField(
            model_name='historicalmarketgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
