# Generated by Django 3.2.5 on 2023-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20230107_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='masked_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcarddetail',
            name='masked_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
