# Generated by Django 3.2.5 on 2023-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20230109_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarketgroup',
            name='market_group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='market_group',
            field=models.CharField(max_length=255),
        ),
    ]
