# Generated by Django 3.2.5 on 2023-01-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_auto_20230109_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarketgroup',
            name='market_group',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='market_group',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
