# Generated by Django 3.2.5 on 2023-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20230109_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroom',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out of Order', 'Out of Order'), ('Out of Service', 'Out of Service')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out of Order', 'Out of Order'), ('Out of Service', 'Out of Service')], max_length=100),
        ),
    ]
