# Generated by Django 3.2.5 on 2023-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_auto_20230109_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroom',
            name='room_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('inspected', 'Inspected'), ('dirty', 'Dirty'), ('out_of_order', 'Out of Order'), ('out_of_service', 'Out of Service')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('inspected', 'Inspected'), ('dirty', 'Dirty'), ('out_of_order', 'Out of Order'), ('out_of_service', 'Out of Service')], max_length=100),
        ),
    ]
