# Generated by Django 3.2.5 on 2023-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20230109_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroomdiscrepancy',
            name='reservation_status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Departed', 'Departed'), ('Stay Over', 'Stay Over'), ('Arrivals', 'Arrivals'), ('Not Reserved', 'Not Reserved'), ('Arrived', 'Arrived'), ('Due Out', 'Due Out'), ('Due Out / Arrivals', 'Due Out / Arrivals')], default='Not Reserved', max_length=100),
        ),
        migrations.AddField(
            model_name='roomdiscrepancy',
            name='reservation_status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Departed', 'Departed'), ('Stay Over', 'Stay Over'), ('Arrivals', 'Arrivals'), ('Not Reserved', 'Not Reserved'), ('Arrived', 'Arrived'), ('Due Out', 'Due Out'), ('Due Out / Arrivals', 'Due Out / Arrivals')], default='Not Reserved', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='front_office_status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='reservation_status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Departed', 'Departed'), ('Stay Over', 'Stay Over'), ('Arrivals', 'Arrivals'), ('Not Reserved', 'Not Reserved'), ('Arrived', 'Arrived'), ('Due Out', 'Due Out'), ('Due Out / Arrivals', 'Due Out / Arrivals')], default='Not Reserved', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalroom',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out Of Order', 'Out Of Order'), ('Out Of Service', 'Out Of Service')], default='Dirty', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalroomdiscrepancy',
            name='front_office_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='Vacant', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalroomdiscrepancy',
            name='housekeeping_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out Of Order', 'Out Of Order'), ('Out Of Service', 'Out Of Service')], default='Dirty', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='front_office_status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='reservation_status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Departed', 'Departed'), ('Stay Over', 'Stay Over'), ('Arrivals', 'Arrivals'), ('Not Reserved', 'Not Reserved'), ('Arrived', 'Arrived'), ('Due Out', 'Due Out'), ('Due Out / Arrivals', 'Due Out / Arrivals')], default='Not Reserved', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out Of Order', 'Out Of Order'), ('Out Of Service', 'Out Of Service')], default='Dirty', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomdiscrepancy',
            name='front_office_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='Vacant', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomdiscrepancy',
            name='housekeeping_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out Of Order', 'Out Of Order'), ('Out Of Service', 'Out Of Service')], default='Dirty', max_length=100),
        ),
    ]
