# Generated by Django 3.2.5 on 2023-01-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20230109_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroom',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out Of Order', 'Out Of Order'), ('Out Of Service', 'Out Of Service')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Inspected', 'Inspected'), ('Dirty', 'Dirty'), ('Out Of Order', 'Out Of Order'), ('Out Of Service', 'Out Of Service')], max_length=100),
        ),
    ]
