# Generated by Django 3.2.5 on 2023-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_auto_20230110_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreservation',
            name='block_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
