# Generated by Django 3.2.5 on 2023-01-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_auto_20230110_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='group',
            field=models.ManyToManyField(null=True, to='reservations.Group'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.subgroup'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Amount'), ('pieces', 'Pieces'), ('trips', 'Trips')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextra',
            name='type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Amount'), ('pieces', 'Pieces'), ('trips', 'Trips')], max_length=255, null=True),
        ),
    ]
