# Generated by Django 3.2.5 on 2023-01-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_auto_20230110_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackage',
            name='calculation_rule',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_adult', 'Per Adult'), ('per_room', 'Per Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='posting_rhythm',
            field=models.CharField(choices=[('post_every_night', 'Post Every Night'), ('post_on_arrival_night', 'Post on Arrival Night'), ('post_on_every_x_night_starting_y_night', 'Post on Every X Night Starting Y Night'), ('post_on_certain_nights_of_the_week', 'Post on Certain Nights of the week'), ('post_last_night', 'Post Last Night'), ('post_every_night_except_arrival_night', 'Post Every Night Except Arrival Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='calculation_rule',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_adult', 'Per Adult'), ('per_room', 'Per Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='posting_rhythm',
            field=models.CharField(choices=[('post_every_night', 'Post Every Night'), ('post_on_arrival_night', 'Post on Arrival Night'), ('post_on_every_x_night_starting_y_night', 'Post on Every X Night Starting Y Night'), ('post_on_certain_nights_of_the_week', 'Post on Certain Nights of the week'), ('post_last_night', 'Post Last Night'), ('post_every_night_except_arrival_night', 'Post Every Night Except Arrival Night')], max_length=50),
        ),
    ]
