# Generated by Django 3.2.5 on 2023-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_auto_20230110_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
