# Generated by Django 3.2.5 on 2023-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_auto_20230110_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackage',
            name='calculation_rule',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_adult', 'Per Adult'), ('per_room', 'Per Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='calculation_rule',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_adult', 'Per Adult'), ('per_room', 'Per Room')], max_length=20),
        ),
    ]
