# Generated by Django 3.2.5 on 2023-01-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_auto_20230117_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_details', to='reservations.reservation'),
        ),
    ]
