# Generated by Django 3.2.5 on 2023-01-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_booker_account'),
        ('reservations', '0028_alter_dailydetail_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='company_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='accounts.guestprofile'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='reservations.reservation'),
        ),
    ]
