# Generated by Django 3.2.5 on 2023-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_auto_20230111_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=255, unique=True)),
                ('applies_form', models.DateField()),
                ('exempt_after', models.IntegerField()),
                ('posting_type', models.CharField(choices=[('Slab', 'Slab')], default='Slab', max_length=100)),
                ('no_of_slab', models.IntegerField()),
            ],
        ),
    ]
