# Generated by Django 3.2.5 on 2023-01-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_booker_account'),
        ('reservations', '0029_auto_20230118_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forexes', to='accounts.guestprofile'),
        ),
        migrations.AlterField(
            model_name='forex',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forexes', to='reservations.reservation'),
        ),
    ]
