# Generated by Django 3.2.5 on 2023-01-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0030_auto_20230110_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalratecode',
            old_name='complimentary',
            new_name='complementary',
        ),
        migrations.RenameField(
            model_name='ratecode',
            old_name='complimentary',
            new_name='complementary',
        ),
    ]
