# Generated by Django 3.2.5 on 2023-01-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_auto_20230111_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackage',
            name='posting_rhythm',
            field=models.CharField(choices=[('post_every_night', 'Post Every Night'), ('post_on_arrival_night', 'Post on Arrival Night'), ('post_on_every_x_night_starting_y_night', 'Post on Every X Night Starting Y Night'), ('post_on_certain_nights_of_the_week', 'Post on Certain Nights of the week'), ('post_last_night', 'Post Last Night'), ('post_every_night_except_arrival_night', 'Post Every Night Except Arrival Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='posting_rhythm',
            field=models.CharField(choices=[('post_every_night', 'Post Every Night'), ('post_on_arrival_night', 'Post on Arrival Night'), ('post_on_every_x_night_starting_y_night', 'Post on Every X Night Starting Y Night'), ('post_on_certain_nights_of_the_week', 'Post on Certain Nights of the week'), ('post_last_night', 'Post Last Night'), ('post_every_night_except_arrival_night', 'Post Every Night Except Arrival Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='reservations.group'),
        ),
    ]
