# Generated by Django 3.2.5 on 2023-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_auto_20230112_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='group',
            field=models.ManyToManyField(blank=True, to='reservations.Group'),
        ),
    ]
