# Generated by Django 3.2.5 on 2023-01-12 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0034_alter_extra_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=255, unique=True)),
                ('applies_form', models.DateField()),
                ('exempt_after', models.IntegerField()),
                ('posting_type', models.CharField(choices=[('Slab', 'Slab')], default='Slab', max_length=100)),
                ('no_of_slab', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='calculation_rule',
            field=models.CharField(choices=[('Flat Rate', 'Flat Rate'), ('Per Adult', 'Per Adult'), ('Per Room', 'Per Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='posting_rhythm',
            field=models.CharField(choices=[('Post Every Night', 'Post Every Night'), ('Post on Arrival Night', 'Post on Arrival Night'), ('Post on Every X Night Starting Y Night', 'Post on Every X Night Starting Y Night'), ('Post on Certain Nights of the week', 'Post on Certain Nights of the week'), ('Post Last Night', 'Post Last Night'), ('Post Every Night Except Arrival Night', 'Post Every Night Except Arrival Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='rate_inclusion',
            field=models.CharField(choices=[('Included in rate', 'Included in rate'), ('Add Rate Separate Line', 'Add Rate Separate Line')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='calculation_rule',
            field=models.CharField(choices=[('Flat Rate', 'Flat Rate'), ('Per Adult', 'Per Adult'), ('Per Room', 'Per Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='posting_rhythm',
            field=models.CharField(choices=[('Post Every Night', 'Post Every Night'), ('Post on Arrival Night', 'Post on Arrival Night'), ('Post on Every X Night Starting Y Night', 'Post on Every X Night Starting Y Night'), ('Post on Certain Nights of the week', 'Post on Certain Nights of the week'), ('Post Last Night', 'Post Last Night'), ('Post Every Night Except Arrival Night', 'Post Every Night Except Arrival Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='rate_inclusion',
            field=models.CharField(choices=[('Included in rate', 'Included in rate'), ('Add Rate Separate Line', 'Add Rate Separate Line')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='HistoricalTax',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tax_name', models.CharField(db_index=True, max_length=255)),
                ('applies_form', models.DateField()),
                ('exempt_after', models.IntegerField()),
                ('posting_type', models.CharField(choices=[('Slab', 'Slab')], default='Slab', max_length=100)),
                ('no_of_slab', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tax',
                'verbose_name_plural': 'historical taxs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
