# Generated by Django 3.2.5 on 2023-01-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0035_auto_20230112_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreservation',
            name='room_to_charge',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_to_charge',
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='booking_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='room_type_to_charge',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.roomtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type_to_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_to_charge_reservations', to='reservations.roomtype'),
        ),
    ]
