# Generated by Django 3.2.5 on 2023-01-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0036_auto_20230113_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_group', models.TextField(unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='groupreservation',
            name='block_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250, unique=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, unique=True)),
                ('gst', models.CharField(choices=[('5', '5'), ('18', '18'), ('8', '8')], max_length=50)),
                ('kg_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('menu_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratecards', to='reservations.linens')),
            ],
        ),
    ]
