# Generated by Django 3.2.5 on 2023-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0037_auto_20230113_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='kg_status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10),
        ),
    ]
