# Generated by Django 3.2.5 on 2023-01-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0039_alter_ratecard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratecard',
            name='menu_group',
        ),
        migrations.DeleteModel(
            name='Linens',
        ),
        migrations.DeleteModel(
            name='RateCard',
        ),
    ]
