# Generated by Django 3.2.5 on 2023-01-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0040_auto_20230116_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='transaction_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentTypes', to='reservations.transactioncode'),
        ),
    ]
