# Generated by Django 3.2.5 on 2023-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0042_auto_20230116_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
