# Generated by Django 3.2.5 on 2023-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0046_auto_20230116_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
