# Generated by Django 3.2.5 on 2023-01-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_auto_20230116_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
