# Generated by Django 3.2.5 on 2023-01-17 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0048_auto_20230116_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltax',
            name='no_of_slab',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='no_of_slab',
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='apply_on_pax',
            field=models.CharField(blank=True, choices=[('Per Night', 'Per Night'), ('Per Adult', 'Per Adult'), ('Per Child', 'Per Child'), ('Per Pax', 'Per Pax')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='apply_tax',
            field=models.CharField(choices=[('before discount', 'Before Discount'), ('after discount', 'After Discount')], default='before discount', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='apply_tax_on_rack_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='no_of_slabs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='apply_on_pax',
            field=models.CharField(blank=True, choices=[('Per Night', 'Per Night'), ('Per Adult', 'Per Adult'), ('Per Child', 'Per Child'), ('Per Pax', 'Per Pax')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='apply_tax',
            field=models.CharField(choices=[('before discount', 'Before Discount'), ('after discount', 'After Discount')], default='before discount', max_length=100),
        ),
        migrations.AddField(
            model_name='tax',
            name='apply_tax_on_rack_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='no_of_slabs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='groupreservation',
            name='origin',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Walk-in', 'Walk-in'), ('House use', 'House use'), ('Hotel Reservation Office', 'Hotel Reservation Office'), ('EMAIL', 'EMAIL'), ('ONLINE', 'ONLINE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='groupreservation',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Tentative', 'Tentative'), ('Definite', 'Definite')], max_length=10),
        ),
        migrations.AlterField(
            model_name='groupreservation',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltax',
            name='exempt_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicaltax',
            name='posting_type',
            field=models.CharField(choices=[('slab', 'Slab'), ('flat amount', 'Flat Amount'), ('flat percentage', 'Flat Percentage')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tax',
            name='exempt_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tax',
            name='posting_type',
            field=models.CharField(choices=[('slab', 'Slab'), ('flat amount', 'Flat Amount'), ('flat percentage', 'Flat Percentage')], max_length=100),
        ),
        migrations.CreateModel(
            name='TaxGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes_generation', to='reservations.tax')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTaxGeneration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.tax')),
            ],
            options={
                'verbose_name': 'historical tax generation',
                'verbose_name_plural': 'historical tax generations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
