# Generated by Django 3.2.5 on 2023-01-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0049_auto_20230117_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltax',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tax', 'verbose_name_plural': 'historical Taxes'},
        ),
        migrations.AlterModelOptions(
            name='historicaltaxgeneration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tax generation', 'verbose_name_plural': 'historical Taxes Generation'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterModelOptions(
            name='taxgeneration',
            options={'verbose_name_plural': 'Taxes Generation'},
        ),
        migrations.AlterField(
            model_name='historicaltaxgeneration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxgeneration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
