# Generated by Django 3.2.5 on 2023-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0051_auto_20230118_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreservation',
            name='block_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
