# Generated by Django 3.2.5 on 2023-01-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0052_alter_groupreservation_block_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forexes', to='reservations.tax'),
        ),
        migrations.AddField(
            model_name='historicalforex',
            name='tax',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.tax'),
        ),
        migrations.AddField(
            model_name='transactioncode',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='reservations.Tax'),
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_transactions', to='reservations.tax')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='reservations.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTaxTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.tax')),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.transaction')),
            ],
            options={
                'verbose_name': 'historical tax transaction',
                'verbose_name_plural': 'historical tax transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
