# Generated by Django 3.2.5 on 2023-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0052_alter_groupreservation_block_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicaldailydetail',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
