# Generated by Django 3.2.5 on 2023-01-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0053_auto_20230120_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='reservations.room'),
        ),
    ]
