# Generated by Django 3.2.5 on 2023-01-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0058_alter_transaction_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='folio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reservations.folio'),
        ),
    ]
