# Generated by Django 3.2.5 on 2023-01-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0060_auto_20230127_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.folio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation'),
        ),
    ]
