# Generated by Django 3.2.5 on 2023-02-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20230203_1418'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasserby',
            name='room_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.roomclass'),
        ),
        migrations.AddField(
            model_name='passerby',
            name='room_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passers_by', to='reservations.roomclass'),
        ),
    ]
