# Generated by Django 3.2.5 on 2022-12-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221226_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_front_office',
            new_name='is_account_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_housekeeping',
        ),
    ]
