# Generated by Django 3.2.5 on 2022-12-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221226_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
