# Generated by Django 3.2.5 on 2023-01-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230107_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalIDDetails',
            new_name='HistoricalIDDetail',
        ),
        migrations.RenameModel(
            old_name='HistoricalVisaDetails',
            new_name='HistoricalVisaDetail',
        ),
        migrations.RenameModel(
            old_name='IDDetails',
            new_name='IDDetail',
        ),
        migrations.RenameModel(
            old_name='VisaDetails',
            new_name='VisaDetail',
        ),
        migrations.AlterModelOptions(
            name='historicaliddetail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical id detail', 'verbose_name_plural': 'historical id details'},
        ),
        migrations.AlterModelOptions(
            name='historicalpasserby',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical passer by', 'verbose_name_plural': 'historical Passers By'},
        ),
        migrations.AlterModelOptions(
            name='historicalvisadetail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical visa detail', 'verbose_name_plural': 'historical visa details'},
        ),
        migrations.AlterModelOptions(
            name='passerby',
            options={'verbose_name_plural': 'Passers By'},
        ),
    ]
