# Generated by Django 3.2.5 on 2023-01-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230110_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookers', to='accounts.account'),
        ),
    ]
