# Generated by Django 3.2.5 on 2023-01-17 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230112_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='guest_status',
            field=models.CharField(blank=True, choices=[('In House', 'In House'), ('Out', 'Out')], default='Out', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalguestprofile',
            name='guest_status',
            field=models.CharField(blank=True, choices=[('In House', 'In House'), ('Out', 'Out')], default='Out', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Company', 'Company'), ('Travel Agent', 'Travel Agent'), ('Group', 'Group')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booker',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookers', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Capt', 'Capt'), ('Wg Cdr', 'Wg Cdr'), ('Major', 'Major'), ('Colonel', 'Colonel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='account_type',
            field=models.CharField(choices=[('Company', 'Company'), ('Travel Agent', 'Travel Agent'), ('Group', 'Group')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguestprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguestprofile',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Capt', 'Capt'), ('Wg Cdr', 'Wg Cdr'), ('Major', 'Major'), ('Colonel', 'Colonel')], max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_number', models.CharField(db_index=True, max_length=255)),
                ('name_on_card', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('guest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.guestprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership_level', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.membershiplevel')),
                ('membership_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.membershiptype')),
            ],
            options={
                'verbose_name': 'historical membership',
                'verbose_name_plural': 'historical memberships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
