# Generated by Django 3.2.5 on 2023-01-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_booker_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookers', to='accounts.account'),
        ),
    ]
