# Generated by Django 3.2.5 on 2023-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230116_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='guest_status',
            field=models.CharField(blank=True, choices=[('In House', 'In House'), ('Out', 'Out')], default='Out', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguestprofile',
            name='guest_status',
            field=models.CharField(blank=True, choices=[('In House', 'In House'), ('Out', 'Out')], default='Out', max_length=255, null=True),
        ),
    ]
