# Generated by Django 3.2.5 on 2023-01-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mast', 'Mast'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Capt', 'Capt'), ('Wg Cdr', 'Wg Cdr'), ('Major', 'Major'), ('Colonel', 'Colonel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalguestprofile',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mast', 'Mast'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Capt', 'Capt'), ('Wg Cdr', 'Wg Cdr'), ('Major', 'Major'), ('Colonel', 'Colonel')], max_length=10),
        ),
    ]
