# Generated by Django 3.2.5 on 2023-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230118_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
