# Generated by Django 3.2.5 on 2023-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20230124_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='is_black_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalguestprofile',
            name='is_black_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmembershiplevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalmembershiptype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiplevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
